export const CALL_API = 'CALL_API'

export const GET_USER_LIST_REQUEST = 'GET_USER_LIST_REQUEST'
export const GET_USER_LIST_SUCCESS = 'GET_USER_LIST_SUCCESS'
export const GET_USER_LIST_ERROR = 'GET_USER_LIST_ERROR'

export const GET_USER_POST_REQUEST = 'GET_USER_POST_REQUEST'
export const GET_USER_POST_SUCCESS = 'GET_USER_POST_SUCCESS'
export const GET_USER_POST_ERROR = 'GET_USER_POST_ERROR'

export const DELETE_USER_POST_REQUEST = 'DELETE_USER_POST_REQUEST'
export const DELETE_USER_POST_SUCCESS = 'DELETE_USER_POST_SUCCESS'
export const DELETE_USER_POST_ERROR = 'DELETE_USER_POST_ERROR'

export const ADD_USER_POST_REQUEST = 'ADD_USER_POST_REQUEST'
export const ADD_USER_POST_SUCCESS = 'ADD_USER_POST_SUCCESS'
export const ADD_USER_POST_ERROR = 'ADD_USER_POST_ERROR'
